### ISSUE TITLE
Cannot run this repo

### ISSUE THREAD

**Issue by bahmutov** [dangi13/flaky-test-cypress#1]
Hello, I am trying to run this repo, but there are always some kind of errors preventing the app from starting or loading. Could you update the repo to the latest react / react-scripts by any chance?

**Comment by dangi13** [comment]
Hey, as you can see its not my original repo ;) and I cloned it at that time from Internet. But I have fixed the start issue and its opening and loading good now. Let me know if its working for you as well.

**Comment by bahmutov** [comment]
Super, the app is working, but I never see a failing test, always passes, maybe I'm just lucky

**Comment by dangi13** [comment]
Yeah I fixed that at that time. To get back the flakiness behavior you can just comment out line number 25 in test (app_spec.js) and you should have it in few tries.

`cy.get('input[value="Saved!"]', { timeout: 4501 }).should('be.visible')`;
